In [ ]:
import numpy as np

lst = [2, 6, 1, 5]
arr = np.array(lst)
print("Type of arr:", type(arr))  # Just to confirm arr is a NumPy array


Type of arr: <class 'numpy.ndarray'>


In [ ]:
lst1 = [1, 2, 3, 4, 5]
lst2 = [5, 6, 7, 8, 9]
lst3 = [11, 12, 13, 14, 15]

arr = np.array([lst1, lst2, lst3])
print("2D array:\n", arr)


2D array:
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [11 12 13 14 15]]


In [ ]:
print("Element at row 1, column 3:", arr[1, 3])  # Access element

arr[2, 4] = 16  # Change value at 3rd row, 5th column
print("Array after change:\n", arr)


Element at row 1, column 3: 8
Array after change:
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [11 12 13 14 16]]


In [ ]:
print("Slice of array (rows 0-1, cols 2-3):\n", arr[0:2, 2:4])


Slice of array (rows 0-1, cols 2-3):
 [[3 4]
 [7 8]]


In [ ]:
print("Elements less than 4:\n", arr[arr < 4])


Elements less than 4:
 [1 2 3]


In [ ]:
reshaped = arr.reshape(5, 3)
print("Reshaped array (5 rows, 3 columns):\n", reshaped)


Reshaped array (5 rows, 3 columns):
 [[ 1  2  3]
 [ 4  5  5]
 [ 6  7  8]
 [ 9 11 12]
 [13 14 16]]


In [ ]:
range_arr = np.arange(1, 10, 2)
print("Array with steps of 2:", range_arr)


Array with steps of 2: [1 3 5 7 9]


In [ ]:
reshaped_3d = np.arange(1, 20, 2).reshape(5, 2, 1)
print("3D array:\n", reshaped_3d)


3D array:
 [[[ 1]
  [ 3]]

 [[ 5]
  [ 7]]

 [[ 9]
  [11]]

 [[13]
  [15]]

 [[17]
  [19]]]


In [ ]:
list1 = [1, 2, 3, 4, 5]
arr2 = np.array(list1)

print("Squares of elements:", arr2 * arr2)
print("Squares of 2D array elements:\n", arr * arr)


Squares of elements: [ 1  4  9 16 25]
Squares of 2D array elements:
 [[  1   4   9  16  25]
 [ 25  36  49  64  81]
 [121 144 169 196 256]]


In [ ]:
print("Array of ones (5x3):\n", np.ones((5, 3)))
print("Array of zeros (2x3):\n", np.zeros((2, 3)))


Array of ones (5x3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array of zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print("Random integers between 5 and 3100:", np.random.randint(5, 3100, 4))
print("Random normal values (1x2):\n", np.random.randn(1, 2))


Random integers between 5 and 3100: [ 472 1695 2066 1251]
Random normal values (1x2):
 [[ 0.38575299 -1.50452351]]


In [ ]:
# Repeat 1D array three times
lst1 = [1, 2, 3]
arr1 = np.array(lst1)
repeated_arr1d = np.tile(arr1, 3)
print("Repeated 1D array:\n", repeated_arr1d)

# Repeat 2D array twice vertically and thrice horizontally
lst2 = [[2, 6, 1, 5]]
arr2d = np.array(lst2)
repeated_arr2d = np.tile(arr2d, (2, 3))
print("Repeated 2D array:\n", repeated_arr2d)


Repeated 1D array:
 [1 2 3 1 2 3 1 2 3]
Repeated 2D array:
 [[2 6 1 5 2 6 1 5 2 6 1 5]
 [2 6 1 5 2 6 1 5 2 6 1 5]]


In [ ]:
ascending_arr = np.arange(1, 13).reshape(3, 4)
print("Ascending ordered array:\n", ascending_arr)


Ascending ordered array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
